# Generated by Django 4.2.16 on 2024-12-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=100)),
                ('unvan', models.CharField(max_length=200)),
                ('elaqe', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='Magazalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magaza_adi', models.CharField(max_length=100)),
                ('unvan', models.CharField(max_length=200)),
                ('elaqe', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Magazalar',
            },
        ),
        migrations.CreateModel(
            name='Mehsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul_adi', models.CharField(max_length=200)),
                ('magaza', models.CharField(max_length=100)),
                ('standart_satis', models.FloatField()),
                ('top_alis', models.FloatField()),
                ('satis', models.FloatField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asan.firmalar')),
            ],
            options={
                'verbose_name_plural': 'Mehsullar',
            },
        ),
    ]
