# Generated by Django 4.2.16 on 2024-12-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmalar',
            name='unvan',
        ),
        migrations.AddField(
            model_name='firmalar',
            name='magaza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asan.magazalar'),
        ),
    ]
