# Generated by Django 4.2.16 on 2024-12-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asan', '0003_remove_firmalar_elaqe'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmalar',
            name='haqqinda',
            field=models.TextField(blank=True),
        ),
    ]
