# Generated by Django 4.2.16 on 2025-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asan', '0004_firmalar_haqqinda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriya', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mehsullar',
            name='kategoriya',
            field=models.ManyToManyField(to='asan.kategoriya'),
        ),
    ]
