# Generated by Django 4.2.16 on 2025-01-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asan', '0005_kategoriya_mehsullar_kategoriya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.RenameField(
            model_name='kategoriya',
            old_name='kategoriya',
            new_name='adi',
        ),
        migrations.AlterField(
            model_name='mehsullar',
            name='kategoriya',
            field=models.ManyToManyField(related_name='kategoriyalar', to='asan.kategoriya'),
        ),
    ]
