# Generated by Django 4.2.16 on 2025-01-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asan', '0007_remove_mehsullar_kategoriya_kategoriya_mehsul'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoriya',
            old_name='adi',
            new_name='kategoriya',
        ),
        migrations.RemoveField(
            model_name='kategoriya',
            name='mehsul',
        ),
        migrations.AddField(
            model_name='mehsullar',
            name='kategoriya',
            field=models.ManyToManyField(to='asan.kategoriya'),
        ),
    ]
